export const QUESTION_PROTECTED_TERMS = [
  "Aal",
  "Aale",
  "Aitel (Döbel)",
  "Aitel",
  "Aland",
  "Äsche",
  "Äschenregion",
  "Atlantischer Lachs",
  "Armleuchtergewächs",
  "Armleuchtergewächse",
  "AVBayFiG",
  "Bachflohkrebs",
  "Bachflohkrebse",
  "Bachforelle",
  "Bachforellen",
  "Bachmuschel",
  "Bachneunauge",
  "Bachsaibling",
  "Barbe",
  "Barbenregion",
  "Barschartige (Perciden)",
  "BayFiG",
  "Bitterling",
  "Blaufelchen",
  "Brachse",
  "Brachsenregion",
  "Dreistachliger Stichling",
  "Donaukaulbarsch",
  "Dorngrundel",
  "Döbel",
  "Edelkrebs",
  "Elritze",
  "Europakanal",
  "Felchen",
  "Fischereiaufseher",
  "Fischereierlaubnis",
  "Fischereischein",
  "Fischereigesetz",
  "Fischereigesetzes",
  "AVBayFiG",
  "BayFiG",
  "BayFiG",
  "Flussbarsch",
  "Flussperlmuschel",
  "Forellenregion",
  "Frauennerfling",
  "Gänsesäger",
  "Gemeingebrauch",
  "Giebel",
  "Gründling",
  "Große Flussmuschel",
  "Güster",
  "Handangel",
  "Hasel",
  "Hecht",
  "Huchen",
  "Jugendfischereischein",
  "Kaulbarsch",
  "Karausche",
  "Karpfen",
  "Karpfenartigen (Cypriniden)",
  "Kormoran",
  "Krebspest",
  "Kreisverwaltungsbehörde",
  "Laube (Ukelei)",
  "Lachsartigen (Salmoniden)",
  "Laichausschlag",
  "Mairenke (Seelaube)",
  "Malermuschel",
  "Maifisch",
  "Mink",
  "Moderlieschen",
  "Mühlkoppe",
  "Nase",
  "Nerfling (Aland)",
  "Nerfling",
  "Neunauge",
  "Neunaugen",
  "Perciden",
  "Perlfisch",
  "Quappe",
  "Rapfen",
  "Regenbogenforelle",
  "Regenbogenforellen",
  "Reiher",
  "Renke (Felchen)",
  "Rotauge",
  "Rotfeder",
  "Rundmäulern",
  "Rutte (Quappe, Trüsche)",
  "Rutte",
  "Salmoniden",
  "Schied (Rapfen)",
  "Schied",
  "Schlammpeitzger",
  "Schmerle (Bartgrundel)",
  "Schneider",
  "Schonmaß",
  "Schonmaße",
  "Schonzeit",
  "Schonzeiten",
  "Schrätzer",
  "Seeforelle",
  "Seelaube",
  "Seesaibling",
  "Seerüßling",
  "Setzkescher",
  "Sichling",
  "Silagesickersaft",
  "Steinbeißer (Dorngrundel)",
  "Steinbeißer",
  "Steingressling",
  "Steinkrebs",
  "Sterlet",
  "Stichling",
  "Strömer",
  "Streber",
  "Sumpfkrebs",
  "Trüsche",
  "Ukelei",
  "Waller (Wels)",
  "Waller",
  "Wels",
  "Zährte (Seerüßling)",
  "Zährte",
  "Zander",
  "Zingel",
  "Zobel",
  "Zope",
  "Zwergstichling",
  "Zwergwels",
];
